version: 2.1

orbs:
  heroku: circleci/heroku@2.0

jobs:
  build-and-test:
    docker:
      - image: matblanchard/oc_lettings
    steps:
      - checkout
      - run: python3 -m venv env
      - run: source env/bin/activate && pip install -r requirements.txt
      - run: source env/bin/activate && python3 manage.py makemigrations
      - run: source env/bin/activate && python3 manage.py migrate
      - run: source env/bin/activate && flake8
      - run: source env/bin/activate && pytest --cov=.
  push-on-dockerhub:
    machine: true
    steps:
      - checkout
      - run: docker login
      - run: docker build --tag matblanchard/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run: docker push matblanchard/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}
  heroku-deploy:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git

workflows:
  main:
    jobs:
      - build-and-test
      - push-on-dockerhub:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - main
      - heroku-deploy:
          requires:
            - push-on-dockerhub
          filters:
            branches:
              only:
                - main