version: 2.1

jobs:
  build-and-test:
    docker:
      - image: matblanchard/oc_lettings
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: source venv/bin/activate && pip install -r requirements.txt
      - run: source venv/bin/activate && flake8
      - run: source venv/bin/activate && pytest
  push-on-dockerhub:
    machine: true
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username matblanchard --password-stdin
      - run: docker build --tag matblanchard/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1} .
      - run: docker push matblanchard/${CIRCLE_PROJECT_REPONAME}:${CIRCLE_SHA1}

workflows:
  main:
    jobs:
      - build-and-test
      - push-on-dockerhub:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master