version: 2.1

jobs:
  build-and-test:
    docker:
      - image: matblanchard/oc_lettings
    steps:
      - checkout
      - run: python3 -m venv venv
      - run: source venv/bin/activate && pip install -r requirements.txt
      - run: source venv/bin/activate && flake8
      - run: source venv/bin/activate && pytest
  push-on-dockerhub:
    machine: true
  deploy-on-heroku:
    executor: heroku/default
    steps:
      - checkout
      - heroku/deploy-via-git

workflows:
  main:
    jobs:
      - build-and-test
      - push-on-dockerhub:
          requires:
            - build-and-test
          filters:
            branches:
              only:
                - master
      - deploy-on-heroku:
          requires:
            - push-on-dockerhub
          filters:
            branches:
              only:
                - master